version: '3.8'

services:
  main:
    image: salute_main
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "sleep 5 && python main.py"
    networks:
      - salute_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  migrations:
    image: salute_migrations
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: [ "sh", "-c", "until pg_isready -h postgres -p 5432; do sleep 2; done; alembic upgrade head" ]
    networks:
      - salute_network
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  join_worker:
    image: salute_manager
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    command: sh -c "/wait-for-it.sh postgres:5432 -- /wait-for-it.sh redis:6379 -- python workers/join_worker/worker.py"
    networks:
      - salute_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  broadcast_worker:
    image: salute_manager
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    command: sh -c "/wait-for-it.sh postgres:5432 -- /wait-for-it.sh redis:6379 -- python workers/broadcast_worker/worker.py"
    networks:
      - salute_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  broadcast_autoscaler:
    image: salute_manager
    build: .
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "sleep 5 && python workers/broadcast_worker/broadcast_autoscaler.py"
    networks:
      - salute_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  log_worker:
    image: salute_manager
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    command: sh -c "/wait-for-it.sh postgres:5432 -- /wait-for-it.sh redis:6379 -- python workers/log_worker/worker.py"
    networks:
      - salute_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - salute_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - salute_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  salute_network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
  redis_data:
