version: '3.8'

services:
  manager:
    build: .
    container_name: salute_manager
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/salute
      - ALEMBIC_DATABASE_URL=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@postgres:5432/salute
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - SUPPORT_USERNAME=${SUPPORT_USERNAME}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
    command: python managers/manager.py
    restart: unless-stopped

  log_worker:
    build: .
    container_name: salute_log_worker
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/salute
      - ALEMBIC_DATABASE_URL=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@postgres:5432/salute
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - SUPPORT_USERNAME=${SUPPORT_USERNAME}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
    command: python workers/log_worker/worker.py
    restart: unless-stopped

  join_worker:
    build: .
    container_name: salute_join_worker
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/salute
      - ALEMBIC_DATABASE_URL=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@postgres:5432/salute
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - SUPPORT_USERNAME=${SUPPORT_USERNAME}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
    command: python workers/join_worker/worker.py
    restart: unless-stopped

  broadcast_worker:
    build: .
    container_name: salute_broadcast_worker
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/salute
      - ALEMBIC_DATABASE_URL=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@postgres:5432/salute
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - SUPPORT_USERNAME=${SUPPORT_USERNAME}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
    command: python workers/broadcast_worker/worker.py
    restart: unless-stopped

  migrations:
    build: .
    container_name: salute_migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/salute
      - ALEMBIC_DATABASE_URL=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@postgres:5432/salute
    volumes:
      - .:/app
    entrypoint: [ "alembic" ]
    command: upgrade head
    profiles:
      - tools

  postgres:
    image: postgres:15
    container_name: salute_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456}
      - POSTGRES_DB=${POSTGRES_DB:-salute}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: salute_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
